# Generated by Django 5.2.3 on 2025-06-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.CharField(blank=True, max_length=500, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
