# Generated by Django 5.2.3 on 2025-06-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_mood_movie_runtime_movie_streaming_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='affiliate_url',
        ),
        migrations.DeleteModel(
            name='SponsoredMovie',
        ),
    ]
