# Generated by Django 5.2.3 on 2025-06-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_movie_affiliate_url_delete_sponsoredmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20),
        ),
    ]
